### ISSUE TITLE
Error in test command: Both stdout and stderr are not empty for \"xcodebuild\" comman

### ISSUE THREAD

**Issue by funzin** [sweetpad-dev/sweetpad#52]
## Description:
While using the sweetpad extension in VSCode, an error occurs during the execution of the test command. The issue is caused by multiple matching destinations being detected, leading to ambiguous selection and failure in fetching the build settings.

The error occurs automatically when the sweetpad extension tries to run a test build. Here's the error message
`Feature` is a target defined in the Swift Package Manager.

```
{
  "message": "Both stdout and stderr are not empty for \"xcodebuild\" command",
  "level": 2,
  "time": "2024-10-19T01:35:52.823Z",
  "stdout": "[\n\n]",
  "stderr": "--- xcodebuild: WARNING: Using the first of multiple matching destinations:\n{ platform:macOS, arch:arm64e, id:XXXXXXXX-XXXXXXXXXXXX, name:My Mac }\n{ platform:macOS, arch:arm64, id:XXXXXXXX-XXXXXXXXXXXX, name:My Mac }\n{ platform:iOS, arch:arm64, id:XXXXXXXX-XXXXXXXXXXXX, name:TestDevice1 }\n{ platform:iOS, arch:arm64, id:XXXXXXXX-XXXXXXXXXXXX, name:TestDevice2 }\n",
  "command": "xcodebuild",
  "args": [
    "-showBuildSettings",
    "-scheme",
    "Feature",
    "-workspace",
    "/path/to/project/App.xcworkspace",
    "-configuration",
    "Debug",
    "-json"
  ],
  "cwd": "/path/to/project"
}
{
  "message": "Error fetching build settings",
  "level": 3,
  "time": "2024-10-19T01:35:52.823Z",
  "stackTrace": "Error: Error fetching build settings\n    at new qv (/Users/dummyuser/.vscode/extensions/sweetpad.sweetpad-0.1.37/out/extension.js:233:12440)\n    at /Users/dummyuser/.vscode/extensions/sweetpad.sweetpad-0.1.37/out/extension.js:235:27\n    at Generator.next (<anonymous>)\n    at o (/Users/dummyuser/.vscode/extensions/sweetpad.sweetpad-0.1.37/out/extension.js:1:1350)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
  "command": "sweetpad.build.test",
  "error": {}
}

```

**Comment by hyzyla** [comment]
@funzin Could you manually execute this command show me the output?

```bash
xcodebuild \
  -showBuildSettings \
  -scheme Feature \
  -workspace /path/to/project/App.xcworkspace \
  -configuration Debug \
  -json
```

I think you are correct that the problem is due to multiple destinations, but there may also be some additional information in the stdout

**Comment by funzin** [comment]
@hyzyla 

Thank you for you reply.
This is the output log.(with masking id)

```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64e, id:XXXXXXXX-XXXXXXXXXXXXXXX, name:My Mac }
{ platform:macOS, arch:arm64, id:XXXXXXXX-XXXXXXXXXXXXXXX, name:My Mac }
{ platform:macOS, arch:x86_64, id:XXXXXXXX-XXXXXXXXXXXXXXX, name:My Mac }
{ platform:macOS, arch:arm64e, variant:Mac Catalyst, id:XXXXXXXX-XXXXXXXXXXXXXXX, name:My Mac }
{ platform:macOS, arch:arm64, variant:Mac Catalyst, id:XXXXXXXX-XXXXXXXXXXXXXXX, name:My Mac }
{ platform:macOS, arch:x86_64, variant:Mac Catalyst, id:XXXXXXXX-XXXXXXXXXXXXXXX, name:My Mac }
{ platform:macOS, arch:arm64, variant:DriverKit, id:XXXXXXXX-XXXXXXXXXXXXXXX, name:My Mac }
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:XXXXXXXX-XXXXXXXXXXXXXXX, name:My Mac }
{ platform:DriverKit, name:Any DriverKit Host }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:macOS, name:Any Mac }
{ platform:macOS, variant:Mac Catalyst, name:Any Mac }
{ platform:iOS, arch:arm64e, id:XXXXXXXX-XXXXXXXXXXXXXXX, name:funzin }
{ platform:iOS, arch:arm64, id:XXXXXXXX-XXXXXXXXXXXXXXX, name:funzin }
{ platform:iOS Simulator, id:XXXXXXXX-XXXXXXXXXXXXXXX, OS:17.5, name:iPad (6th generation) }
{ platform:iOS Simulator, id:XXXXXXXX-XXXXXXXXXXXXXXX, OS:17.5, name:iPad (6th generation) }
{ platform:iOS Simulator, id:XXXXXXXX-XXXXXXXXXXXXXXX, OS:17.5, name:iPhone 15 Pro }
{ platform:iOS Simulator, id:XXXXXXXX-XXXXXXXXXXXXXXX, OS:17.5, name:iPhone 15 Pro }
{ platform:iOS Simulator, id:XXXXXXXX-XXXXXXXXXXXXXXX, OS:18.0, name:iPhone 16 Pro }
{ platform:iOS Simulator, id:XXXXXXXX-XXXXXXXXXXXXXXX, OS:18.0, name:iPhone 16 Pro }
[
]
```

**Comment by funzin** [comment]
I understand.

It seems that when specifying a module(e.g. `Feature` ) managed by SPM (Swift Package Manager), the `xcodebuild -showBuildSettings` command returns an empty output. As a result, if you attempt to run tests for an SPM-managed module through xcodebuild, the current setup does not allow you to retrieve build settings.

For now, you might need to explore alternative methods to handle test execution for SPM modules

https://github.com/sweetpad-dev/sweetpad/blob/main/src/common/cli/scripts.ts#L136-L185

**Comment by hyzyla** [comment]
Oh, thanks. Information about SPM is super helpful here. Could you make some simple test project with the same structure as your project? Or could you explain how to reproduce this structure?

**Comment by funzin** [comment]
@hyzyla 

Could you check the project?
[SwiftExample.zip](https://github.com/user-attachments/files/17460012/SwiftExample.zip)


When I checked the error again, a different one was output.

```
{
  "message": "Error fetching build settings",
  "level": 3,
  "time": "2024-10-21T11:41:01.213Z",
  "stackTrace": "Error: Error fetching build settings\n    at new Kv (/Users/dummy/.vscode/extensions/sweetpad.sweetpad-0.1.38/out/extension.js:233:12698)\n    at /Users/dummy/.vscode/extensions/sweetpad.sweetpad-0.1.38/out/extension.js:235:27\n    at Generator.next (<anonymous>)\n    at o (/Users/dummy/.vscode/extensions/sweetpad.sweetpad-0.1.38/out/extension.js:1:1377)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
  "command": "sweetpad.build.test",
  "error": {}
}

```

**Comment by rpedretti** [comment]
On the same topic of SPM packages I have an example that fails with

```bash
xcodebuild: error: Failed to build workspace TestProject with scheme TestProject.: Tests in the target “TestProject” can’t be run because “TestProject” isn’t a member of the specified test plan or scheme.
```
 when running specific tests e.g. 

```shell
xcodebuild test-without-building \
    -workspace /Users/rafael.pedretti/sources/TestProject/TestProject.xcodeproj/project.xcworkspace \
    -destination 'platform=iOS Simulator,id=959B32D4-953C-49EB-B093-8A88C0654D92' \
    -scheme TestProject \
    -only-testing\:TestProject/LibOneTests/testExample
```
But if change the `only-testing` to `-only-testing\:/LibOneTests/testExample` it works as expected

[TestProject.zip](https://github.com/user-attachments/files/17493535/TestProject.zip)

**Comment by wang9262** [comment]
> @hyzyla
> 
> Could you check the project? [SwiftExample.zip](https://github.com/user-attachments/files/17460012/SwiftExample.zip)
> 
> When I checked the error again, a different one was output.
> 
> ```
> {
>   "message": "Error fetching build settings",
>   "level": 3,
>   "time": "2024-10-21T11:41:01.213Z",
>   "stackTrace": "Error: Error fetching build settings\n    at new Kv (/Users/dummy/.vscode/extensions/sweetpad.sweetpad-0.1.38/out/extension.js:233:12698)\n    at /Users/dummy/.vscode/extensions/sweetpad.sweetpad-0.1.38/out/extension.js:235:27\n    at Generator.next (<anonymous>)\n    at o (/Users/dummy/.vscode/extensions/sweetpad.sweetpad-0.1.38/out/extension.js:1:1377)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
>   "command": "sweetpad.build.test",
>   "error": {}
> }
> ```

Faced the similar problem here. In my case, I use a package.swift to generate my Xcode project，it throws the same error when i build the related scheme

**Comment by hyzyla** [comment]
Thanks frontage information. I’ll try to check this issue this weekend

**Comment by hyzyla** [comment]
@funzin, could you help me understand how to run tests directly in Xcode? I don’t have much experience working with projects like this

> I understand.
>
> It seems that when specifying a module(e.g. Feature ) managed by SPM (Swift Package Manager), the xcodebuild -showBuildSettings command returns an empty output. As a result, if you attempt to run tests for an SPM-managed module through xcodebuild, the current setup does not allow you to retrieve build settings.
>
> For now, you might need to explore alternative methods to handle test execution for SPM modules

When I select Feature in the scheme and then run tests in the Xcode project, I get the following error:

![CleanShot 2024-11-02 at 16 00 57@2x](https://github.com/user-attachments/assets/2db6265b-344c-4327-8fb9-fd509105a646)

**Comment by hyzyla** [comment]
> But if change the only-testing to -only-testing\:/<Lib name>/<Class name>/<test name> as -only-testing\:/LibOneTests/LibOneTests/testExample it works as expected

This is a key point! As I understand it, to run tests in an SPM package, we need to specify the target name from the `.testTarget` in the `Package.swift` file, rather than using a target from the `xcodebuild -list` command. In the latest version, I've added support for detecting SPM packages and their test targets. Could someone check this on their projects? I'm not entirely sure if this is the right fix for this issue

![CleanShot 2024-11-03 at 13 44 17@2x](https://github.com/user-attachments/assets/586c240b-bb5e-449e-b904-a6f331abefd4)

**Comment by rpedretti** [comment]
I'll have some code by eod today for people to test also. I'm scanning the
project to add all the tests to test explorer a do some other fixes

**Comment by wang9262** [comment]
> > But if change the only-testing to -only-testing:/// as -only-testing:/LibOneTests/LibOneTests/testExample it works as expected
> 
> This is a key point! As I understand it, to run tests in an SPM package, we need to specify the target name from the `.testTarget` in the `Package.swift` file, rather than using a target from the `xcodebuild -list` command. In the latest version, I've added support for detecting SPM packages and their test targets. Could someone check this on their projects? I'm not entirely sure if this is the right fix for this issue
> 
> ![CleanShot 2024-11-03 at 13 44 17@2x](https://private-user-images.githubusercontent.com/7952949/382571777-586c240b-bb5e-449e-b904-a6f331abefd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NDIwMjMsIm5iZiI6MTczMDY0MTcyMywicGF0aCI6Ii83OTUyOTQ5LzM4MjU3MTc3Ny01ODZjMjQwYi1iYjVlLTQ0OWUtYjkwNC1hNmYzMzFhYmVmZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDNUMTM0ODQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjI0NjBmZWRiOTMyODYxNjhkZDZkZDlkNDBjOWQ4YmU3OThjNDJlMDQ1NWZlNGIyYjAwM2JmNWJkYWQ5OTE3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Bbp7Hk1YOSexsnkIPZ0CotKaCGimq2afhnp89bzeujk)

In my case, the problem still exists. You can easily reproduce using this [repo](https://github.com/JohnSundell/Publish?tab=readme-ov-file). The generated folder just using `Package.swift` to generate project
<img width="901" alt="image" src="https://github.com/user-attachments/assets/fbcfb907-a07f-4d6e-8e77-dd9f9d9d8625">

**Comment by rpedretti** [comment]
I have a PR to try to get most of the test data from the project itself: https://github.com/sweetpad-dev/sweetpad/pull/67
