### ISSUE TITLE
Sweetpad issue: No schemes

### ISSUE THREAD

**Issue by oguzkr** [sweetpad-dev/sweetpad#53]
Please describe your issue here.

Last logs:
```json
{
  "message": "Sentry setup",
  "level": 1,
  "time": "2024-10-19T07:42:09.923Z",
  "sentryDsn": "https://5f6c5f5f15492a077f6bac254c6d8461@o325723.ingest.us.sentry.io/4507950563328000",
  "sentryIsEnabled": false,
  "sentryIsClientIsInitialized": true
}
{
  "message": "Failed to get schemes",
  "level": 3,
  "time": "2024-10-19T07:42:09.939Z",
  "stackTrace": "Error: Error executing \"xcodebuild\" command\n    at /Users/oguz/.vscode/extensions/sweetpad.sweetpad-0.1.37/out/extension.js:233:5783\n    at Generator.throw (<anonymous>)\n    at s (/Users/oguz/.vscode/extensions/sweetpad.sweetpad-0.1.37/out/extension.js:1:1394)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
  "error": {
    "options": {
      "context": {
        "errorMessage": "Command failed with exit code 1: xcodebuild -list -json -workspace /Users/oguz/Documents/GitHub/iRead/iRead.xcodeproj/project.xcworkspace",
        "stderr": "xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance",
        "command": "xcodebuild",
        "args": [
          "-list",
          "-json",
          "-workspace",
          "/Users/oguz/Documents/GitHub/iRead/iRead.xcodeproj/project.xcworkspace"
        ],
        "cwd": "/Users/oguz/Documents/GitHub/iRead"
      }
    }
  }
}
```

**Comment by hyzyla** [comment]
Hello! Thanks for reporting the problem. The extension relying on `xcodebuild` cli tool. You probably need to install Xcode, or switch to active directory `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer`. Also you can use ` xcode-select --print-path` to check path to active xcode

**Comment by hyzyla** [comment]
Sorry for the slow reply here. I'm cleaning up the backlog and closing this one. Feel free to reopen if it's still worth a look.
