### ISSUE TITLE
Sweetpad issue: No schemes

### ISSUE THREAD

**Issue by barbaracohenzita** [sweetpad-dev/sweetpad#93]
Please describe your issue here.

Last logs:
```json
{
  "message": "Sentry setup",
  "level": 1,
  "time": "2024-12-18T03:42:28.664Z",
  "sentryDsn": "https://5f6c5f5f15492a077f6bac254c6d8461@o325723.ingest.us.sentry.io/4507950563328000",
  "sentryIsEnabled": false,
  "sentryIsClientIsInitialized": true
}
{
  "message": "Failed to get schemes",
  "level": 3,
  "time": "2024-12-18T04:00:15.130Z",
  "stackTrace": "Error: Error executing \"xcodebuild\" command\n    at /Users/space/.vscode/extensions/sweetpad.sweetpad-0.1.46/out/extension.js:47427:13\n    at Generator.throw (<anonymous>)\n    at rejected (/Users/space/.vscode/extensions/sweetpad.sweetpad-0.1.46/out/extension.js:81:29)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
  "error": {
    "options": {
      "context": {
        "errorMessage": "Command failed with exit code 1: xcodebuild -list -json",
        "stderr": "xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance",
        "command": "xcodebuild",
        "args": [
          "-list",
          "-json"
        ],
        "cwd": "/Users/space/Pasta Sem Título"
      }
    }
  }
}
{
  "message": "No xcode workspaces found",
  "level": 3,
  "time": "2024-12-18T04:00:17.138Z",
  "stackTrace": "Error: No xcode workspaces found\n    at /Users/space/.vscode/extensions/sweetpad.sweetpad-0.1.46/out/extension.js:46436:13\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/space/.vscode/extensions/sweetpad.sweetpad-0.1.46/out/extension.js:74:24)",
  "command": "sweetpad.build.selectXcodeWorkspace",
  "errorContext": {
    "cwd": "/Users/space/Pasta Sem Título"
  },
  "error": {
    "options": {
      "context": {
        "cwd": "/Users/space/Pasta Sem Título"
      }
    }
  }
}
```

**Comment by hyzyla** [comment]
@barbaracohenzita  could you try solution from this comment https://github.com/sweetpad-dev/sweetpad/issues/3#issuecomment-2017742269?
