### ISSUE TITLE
Sweetpad issue: No schemes

### ISSUE THREAD

**Issue by faatihusta** [sweetpad-dev/sweetpad#94]
Please describe your issue here.

Last logs:
```json
{
  "message": "Sentry setup",
  "level": 1,
  "time": "2024-12-18T13:32:49.701Z",
  "sentryDsn": "https://5f6c5f5f15492a077f6bac254c6d8461@o325723.ingest.us.sentry.io/4507950563328000",
  "sentryIsEnabled": false,
  "sentryIsClientIsInitialized": true
}
{
  "message": "Failed to get schemes",
  "level": 3,
  "time": "2024-12-18T13:32:50.967Z",
  "stackTrace": "Error: Error executing \"xcodebuild\" command\n    at c:\\Users\\faati\\.vscode\\extensions\\sweetpad.sweetpad-0.1.46\\out\\extension.js:47427:13\n    at Generator.throw (<anonymous>)\n    at rejected (c:\\Users\\faati\\.vscode\\extensions\\sweetpad.sweetpad-0.1.46\\out\\extension.js:81:29)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
  "error": {
    "options": {
      "context": {
        "errorMessage": "Command failed with exit code 1: xcodebuild -list -json",
        "stderr": "'xcodebuild' is not recognized as an internal or external command,\r\noperable program or batch file.",
        "command": "xcodebuild",
        "args": [
          "-list",
          "-json"
        ],
        "cwd": "c:\\Users\\faati\\OneDrive\\Masaüstü\\dekmndekndf"
      }
    }
  }
}
{
  "message": "No xcode workspaces found",
  "level": 3,
  "time": "2024-12-18T13:32:51.883Z",
  "stackTrace": "Error: No xcode workspaces found\n    at c:\\Users\\faati\\.vscode\\extensions\\sweetpad.sweetpad-0.1.46\\out\\extension.js:46436:13\n    at Generator.next (<anonymous>)\n    at fulfilled (c:\\Users\\faati\\.vscode\\extensions\\sweetpad.sweetpad-0.1.46\\out\\extension.js:74:24)",
  "command": "sweetpad.build.selectXcodeWorkspace",
  "errorContext": {
    "cwd": "c:\\Users\\faati\\OneDrive\\Masaüstü\\dekmndekndf"
  },
  "error": {
    "options": {
      "context": {
        "cwd": "c:\\Users\\faati\\OneDrive\\Masaüstü\\dekmndekndf"
      }
    }
  }
}
```

**Comment by hyzyla** [comment]
Duplicate https://github.com/sweetpad-dev/sweetpad/issues/95
