### ISSUE TITLE
Sweetpad issue: No schemes

### ISSUE THREAD

**Issue by faatihusta** [sweetpad-dev/sweetpad#95]
Please describe your issue here.

Last logs:
```json
{
  "message": "Failed to get schemes",
  "level": 3,
  "time": "2024-12-18T13:32:50.967Z",
  "stackTrace": "Error: Error executing \"xcodebuild\" command\n    at c:\\Users\\faati\\.vscode\\extensions\\sweetpad.sweetpad-0.1.46\\out\\extension.js:47427:13\n    at Generator.throw (<anonymous>)\n    at rejected (c:\\Users\\faati\\.vscode\\extensions\\sweetpad.sweetpad-0.1.46\\out\\extension.js:81:29)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
  "error": {
    "options": {
      "context": {
        "errorMessage": "Command failed with exit code 1: xcodebuild -list -json",
        "stderr": "'xcodebuild' is not recognized as an internal or external command,\r\noperable program or batch file.",
        "command": "xcodebuild",
        "args": [
          "-list",
          "-json"
        ],
        "cwd": "c:\\Users\\faati\\OneDrive\\Masaüstü\\dekmndekndf"
      }
    }
  }
}
{
  "message": "No xcode workspaces found",
  "level": 3,
  "time": "2024-12-18T13:32:51.883Z",
  "stackTrace": "Error: No xcode workspaces found\n    at c:\\Users\\faati\\.vscode\\extensions\\sweetpad.sweetpad-0.1.46\\out\\extension.js:46436:13\n    at Generator.next (<anonymous>)\n    at fulfilled (c:\\Users\\faati\\.vscode\\extensions\\sweetpad.sweetpad-0.1.46\\out\\extension.js:74:24)",
  "command": "sweetpad.build.selectXcodeWorkspace",
  "errorContext": {
    "cwd": "c:\\Users\\faati\\OneDrive\\Masaüstü\\dekmndekndf"
  },
  "error": {
    "options": {
      "context": {
        "cwd": "c:\\Users\\faati\\OneDrive\\Masaüstü\\dekmndekndf"
      }
    }
  }
}
{
  "message": "No xcode workspaces found",
  "level": 3,
  "time": "2024-12-18T13:33:09.258Z",
  "stackTrace": "Error: No xcode workspaces found\n    at c:\\Users\\faati\\.vscode\\extensions\\sweetpad.sweetpad-0.1.46\\out\\extension.js:46436:13\n    at Generator.next (<anonymous>)\n    at fulfilled (c:\\Users\\faati\\.vscode\\extensions\\sweetpad.sweetpad-0.1.46\\out\\extension.js:74:24)",
  "command": "sweetpad.build.selectXcodeWorkspace",
  "errorContext": {
    "cwd": "c:\\Users\\faati\\OneDrive\\Masaüstü\\dekmndekndf"
  },
  "error": {
    "options": {
      "context": {
        "cwd": "c:\\Users\\faati\\OneDrive\\Masaüstü\\dekmndekndf"
      }
    }
  }
}
{
  "message": "Error executing \"xcodebuild\" command",
  "level": 3,
  "time": "2024-12-18T13:33:17.615Z",
  "stackTrace": "Error: Error executing \"xcodebuild\" command\n    at c:\\Users\\faati\\.vscode\\extensions\\sweetpad.sweetpad-0.1.46\\out\\extension.js:47427:13\n    at Generator.throw (<anonymous>)\n    at rejected (c:\\Users\\faati\\.vscode\\extensions\\sweetpad.sweetpad-0.1.46\\out\\extension.js:81:29)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
  "command": "sweetpad.build.refreshView",
  "errorContext": {
    "errorMessage": "Command failed with exit code 1: xcodebuild -list -json",
    "stderr": "'xcodebuild' is not recognized as an internal or external command,\r\noperable program or batch file.",
    "command": "xcodebuild",
    "args": [
      "-list",
      "-json"
    ],
    "cwd": "c:\\Users\\faati\\OneDrive\\Masaüstü\\dekmndekndf"
  },
  "error": {
    "options": {
      "context": {
        "errorMessage": "Command failed with exit code 1: xcodebuild -list -json",
        "stderr": "'xcodebuild' is not recognized as an internal or external command,\r\noperable program or batch file.",
        "command": "xcodebuild",
        "args": [
          "-list",
          "-json"
        ],
        "cwd": "c:\\Users\\faati\\OneDrive\\Masaüstü\\dekmndekndf"
      }
    }
  }
}
{
  "message": "No xcode workspaces found",
  "level": 3,
  "time": "2024-12-18T13:33:18.221Z",
  "stackTrace": "Error: No xcode workspaces found\n    at c:\\Users\\faati\\.vscode\\extensions\\sweetpad.sweetpad-0.1.46\\out\\extension.js:46436:13\n    at Generator.next (<anonymous>)\n    at fulfilled (c:\\Users\\faati\\.vscode\\extensions\\sweetpad.sweetpad-0.1.46\\out\\extension.js:74:24)",
  "command": "sweetpad.build.openXcode",
  "errorContext": {
    "cwd": "c:\\Users\\faati\\OneDrive\\Masaüstü\\dekmndekndf"
  },
  "error": {
    "options": {
      "context": {
        "cwd": "c:\\Users\\faati\\OneDrive\\Masaüstü\\dekmndekndf"
      }
    }
  }
}
```

**Comment by hyzyla** [comment]
Hello! Sorry for the inconvenience. It seems like you are trying to run it on a Windows machine. Unfortunately, the extension requires Xcode, so it will only work on macOS machines
